/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/
#pragma once
#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "OscillatorComponent.h"
#include "FilterComponent.h"
#include "LFOComponent.h"

//==============================================================================
/** Class that acts as the GUI for the SimpleSuperSynthAudioProcessor.
*/

class SuperSynthAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    enum
    {
        paramControlHeight = 54,
        paramLabelHeight   = 20,
        paramLabelWidth    = 60,
        paramSliderWidth   = 60
    };

    typedef AudioProcessorValueTreeState::SliderAttachment SliderAttachment;
    typedef AudioProcessorValueTreeState::ButtonAttachment ButtonAttachment;
    
    SuperSynthAudioProcessorEditor (AudioProcessor& parent, AudioProcessorValueTreeState& vts);

    ~SuperSynthAudioProcessorEditor();

    void resized() override;
    
    /** Implementation of the AudioProcessorEditor method. */

    void paint (Graphics& g) override;
    
    /** Implementation of the AudioProcessorEditor method. */
    
private:
    AudioProcessorValueTreeState& valueTreeState; 
    OscillatorComponent * oscillator;
    FilterComponent * filter;
};
